{% set version = "0.3.0" %}

package:
  name: prosolo
  version: {{ version }}

build:
  # only on OSX, `cargo install` fails with: `thread 'main' panicked at 'assertion failed: src_path.is_absolute()', src/tools/cargo/src/cargo/core/manifest.rs:311`
  # looks like a `cargo` bug, that may go away with newer `rust` versions; check osx with rust>1.19 when available
  #  skip: True # [not linux64]
  number: 0
  string: "gsl{{CONDA_GSL}}_{{PKG_BUILDNUM}}"

source:
  url: https://github.com/PROSIC/prosolo/archive/v{{ version }}.tar.gz
  fn: prosolo-{{ version }}.tar.gz
  md5: 485a1578f4464190da0007e644e8182a  

requirements:
  build:
    - gcc # [not osx]
    - llvm # [osx]
    - rust >=1.18
    - gsl {{CONDA_GSL}}*
    - zlib {{ CONDA_ZLIB }}*
  run:
    - gsl {{CONDA_GSL}}*
    - libgcc # [not osx]
    - zlib {{ CONDA_ZLIB }}*

test:
  commands:
    - prosolo single-cell-bulk --help

about:
  home: https://github.com/PROSIC/prosolo/tree/v{{ version }}
  license: GPLv3
  summary: A highly sensitive and accurate Bayesian caller for variants in single cell sequencing data.
