{% set version = "0.3.1" %}

package:
  name: prosolo
  version: {{ version }}

build:
  number: 0
  string: "gsl{{CONDA_GSL}}_{{PKG_BUILDNUM}}"

source:
  url: https://github.com/PROSIC/prosolo/archive/v{{ version }}.tar.gz
  fn: prosolo-{{ version }}.tar.gz
  md5: 57c767cda5c796fc689928cf21e88cdf

requirements:
  build:
    - gcc # [not osx]
    - llvm # [osx]
    - rust >=1.18
    - gsl {{CONDA_GSL}}*
    - zlib {{ CONDA_ZLIB }}*
    # new cram dependencies for rust-htslib 0.16.0
    - bzip2 {{ CONDA_BZIP2 }}*  # [linux]
    - xz
    - clangdev
  run:
    - gsl {{CONDA_GSL}}*
    - libgcc # [not osx]
    - zlib {{ CONDA_ZLIB }}*
    # new cram dependencies for rust-htslib 0.16.0
    - bzip2 {{ CONDA_BZIP2 }}*  # [linux]
    - xz
    - clangdev

test:
  commands:
    - prosolo single-cell-bulk --help

about:
  home: https://github.com/PROSIC/prosolo/tree/v{{ version }}
  license: GPLv3
  summary: A highly sensitive and accurate Bayesian caller for variants in single cell sequencing data.
